# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-shebang-scripts-are-executable
      - id: check-added-large-files
        args: [--maxkb=700]
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: check-symlinks
      - id: check-toml
      - id: debug-statements

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.1
    hooks:
      - id: remove-tabs

  - repo: https://github.com/sirosen/texthooks
    rev: 0.3.1
    hooks:
      - id: fix-smartquotes

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: [--line-length=120]
        exclude: migrations/

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [--profile=black]

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: pretty-format-toml
        args: [--autofix]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.1
    hooks:
      - id: codespell
