---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=500]
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: file-contents-sorter
        files: \.gitignore
      - id: pretty-format-json
        args: [--autofix, --indent=4, --no-sort-keys]
      - id: requirements-txt-fixer
        args:
          [
            requirements.txt,
            requirements-dev.txt,
            requirements-test.txt,
            requirements.in,
          ]
      - id: sort-simple-yaml
        files: (.isort.cfg|setup.cfg)
      - id: trailing-whitespace

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.4.2
    hooks:
      - id: remove-tabs

  - repo: https://github.com/sirosen/texthooks
    rev: 0.5.0
    hooks:
      - id: fix-smartquotes

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py310-plus]

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args: [--line-length=120]

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4 # Note we can't use 6 yet, because the dependencies don't support it
    hooks:
      - id: flake8
        additional_dependencies:
          [
            flake8-bandit,
            flake8-bugbear,
            flake8-debugger,
            flake8-eradicate,
            flake8-string-format,
            pep8-naming,
          ]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile=black]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
