---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: [--line-length=120]
        exclude: migrations/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-shebang-scripts-are-executable
      - id: check-added-large-files
        args: ["--maxkb=700"]
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: check-symlinks
      - id: check-toml
      - id: debug-statements
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile=black"]
