[tool.black]
line-length = 120
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.py_cache
  | \.venv
)/
'''

[tool.isort]
profile = "black"
py_version=39
use_parentheses = true
line_length = 120
combine_as_imports = true
lines_between_sections = 0
ignore_whitespace = true
color_output = true
combine_straight_imports = true
